import { PosterLayout } from '../types/domain';

export const moviePosters: PosterLayout[] = [
  {
    id: 1,
    title: 'The Fog',
    src: 'https://image.tmdb.org/t/p/original/12EeSboRofP3CI4SPmMFNNXCbtY.jpg',
    colStart: 'col-start-1',
    rowStart: 'row-start-1',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-3',
  },
  {
    id: 2,
    title: 'Mononoke Hime',
    src: 'https://image.tmdb.org/t/p/original/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg',
    colStart: 'col-start-1',
    rowStart: 'row-start-3',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-3',
  },
  {
    id: 3,
    title: 'Last Action Hero',
    src: 'https://image.tmdb.org/t/p/original/neVhDxYVsmMMSuhXpHMT3LMK9f.jpg',
    colStart: 'col-start-3',
    rowStart: 'row-start-3',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-3',
  },
  {
    id: 4,
    title: 'Forbidden Planet',
    src: 'https://image.tmdb.org/t/p/original/urQWovdsxmLArvYqG0K2Xg8TTgL.jpg',
    colStart: 'col-start-2',
    rowStart: 'row-start-4',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-3',
  },
  {
    id: 5,
    title: 'The Blob',
    src: 'https://image.tmdb.org/t/p/original/tH4Jvr2Rg7UQFqcndE6Mws4p7sP.jpg',
    colStart: 'col-start-4',
    rowStart: 'row-start-3',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-5',
  },
  {
    id: 6,
    title: 'Pee Wee',
    src: 'https://image.tmdb.org/t/p/original/nvjoIZR6vuYAhip9hGdQGW7C58Y.jpg',
    colStart: 'col-start-5',
    rowStart: 'row-start-5',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-2',
  },
  {
    id: 7,
    title: 'Blade Runner',
    src: 'https://image.tmdb.org/t/p/original/6qrG8bUMAH9sMJOpNoXnAXJ6e6M.jpg',
    colStart: 'col-start-2',
    rowStart: 'row-start-1',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-2',
  },
  {
    id: 8,
    title: 'Wolf Man BW',
    src: 'https://image.tmdb.org/t/p/original/zQJj9jn7rGdizesmm2t2G3Ebea3.jpg',
    colStart: 'col-start-6',
    rowStart: 'row-start-4',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-3',
    rounding: 'rounded-t-2xl',
  },
  {
    id: 9,
    title: 'Zone',
    src: 'https://image.tmdb.org/t/p/original/y5zEw7dMz6e7G0OMbTj6wNqosYa.jpg',
    colStart: 'col-start-6',
    rowStart: 'row-start-6',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-2',
    rounding: 'rounded-b-2xl',
  },
  {
    id: 10,
    title: 'Vertigo',
    src: 'https://image.tmdb.org/t/p/original/mZguodTaXfF1zTTDilYBu4GAIeM.jpg',
    colStart: 'col-start-5',
    rowStart: 'row-start-2',
    colSpan: 'col-span-1',
    rowSpan: 'row-span-3',
  },
];
