import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/app/components/layout/Navbar';
import { Suspense } from 'react';
import ToasterComponent from './components/toast/Toaster';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="sunset">
      <body className={`${geistSans.variable} ${geistMono.variable}  min-h-dvh flex flex-col`}>
        <Suspense>
          <Navbar />
        </Suspense>
        {/* Children (Pages) layer */}
        <main className="flex flex-1 flex-col">
          <ToasterComponent />
          {children}
        </main>
        {/* Modal layer */}
        {modal}
      </body>
    </html>
  );
}
